version: 2
# https://circleci.com/signup/
# You can sign up with github
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      # if react app crashes npm run build wouldn't go through
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing Completed"
      - run: npm install
      - run: npm test
    #Anything within package.json script tag
    #Will Run!
    #So npm coverage could go here...
  package-json-script:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hello package-json-script"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      #Build and test will run in paralell
      - build
      - package-json-script
      # test requires for package-json-script to succeed
      - test:
          requires:
            - package-json-script
