version: 2
# https://circleci.com/signup/
# You can sign up with github
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
